import dotenv from "dotenv";

dotenv.config();

const {
  DISCORD_TOKEN,
  GITHUB_APP_ID,
  GITHUB_APP_PRIVATE_KEY,
  GITHUB_INSTALLATION_ID,
  GITHUB_REPOSITORY,
  DISCORD_CHANNEL_ID,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  PORT
} = process.env;

if (
  !DISCORD_TOKEN ||
  !GITHUB_APP_ID ||
  !GITHUB_APP_PRIVATE_KEY ||
  !GITHUB_INSTALLATION_ID ||
  !GITHUB_REPOSITORY ||
  !DISCORD_CHANNEL_ID
) {
  throw new Error("Missing environment variables");
}

export const config = {
  DISCORD_TOKEN,
  GITHUB_APP_ID,
  GITHUB_APP_PRIVATE_KEY,
  GITHUB_INSTALLATION_ID,
  GITHUB_REPOSITORY,
  DISCORD_CHANNEL_ID,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
};
